// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: email_verification.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const cleanExpiredEmailVerifications = `-- name: CleanExpiredEmailVerifications :exec
DELETE FROM email_verifications
WHERE expires_at < CURRENT_TIMESTAMP OR verified_at IS NOT NULL
`

func (q *Queries) CleanExpiredEmailVerifications(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanExpiredEmailVerifications)
	return err
}

const completeEmailVerification = `-- name: CompleteEmailVerification :one
UPDATE email_verifications
SET verified_at = CURRENT_TIMESTAMP
WHERE user_id = ? AND email = ? AND code = ? AND expires_at > CURRENT_TIMESTAMP
RETURNING id, user_id, email, code, created_at, expires_at, verified_at
`

type CompleteEmailVerificationParams struct {
	UserID string
	Email  string
	Code   string
}

func (q *Queries) CompleteEmailVerification(ctx context.Context, arg CompleteEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRowContext(ctx, completeEmailVerification, arg.UserID, arg.Email, arg.Code)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Code,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.VerifiedAt,
	)
	return i, err
}

const createEmailVerification = `-- name: CreateEmailVerification :exec
INSERT INTO email_verifications (
    user_id,
    email,
    code,
    expires_at
) VALUES (
    ?, ?, ?, ?
) RETURNING id, user_id, email, code, created_at, expires_at, verified_at
`

type CreateEmailVerificationParams struct {
	UserID    string
	Email     string
	Code      string
	ExpiresAt time.Time
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.ExecContext(ctx, createEmailVerification,
		arg.UserID,
		arg.Email,
		arg.Code,
		arg.ExpiresAt,
	)
	return err
}

const getEmailVerification = `-- name: GetEmailVerification :one
SELECT id, code, expires_at, verified_at FROM email_verifications WHERE user_id = ? AND email = ?
`

type GetEmailVerificationParams struct {
	UserID string
	Email  string
}

type GetEmailVerificationRow struct {
	ID         int64
	Code       string
	ExpiresAt  time.Time
	VerifiedAt sql.NullTime
}

func (q *Queries) GetEmailVerification(ctx context.Context, arg GetEmailVerificationParams) (GetEmailVerificationRow, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerification, arg.UserID, arg.Email)
	var i GetEmailVerificationRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ExpiresAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getUserUnverifiedEmailVerifications = `-- name: GetUserUnverifiedEmailVerifications :many
SELECT email, code, created_at, expires_at
FROM email_verifications
WHERE user_id = ? AND verified_at IS NULL
`

type GetUserUnverifiedEmailVerificationsRow struct {
	Email     string
	Code      string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) GetUserUnverifiedEmailVerifications(ctx context.Context, userID string) ([]GetUserUnverifiedEmailVerificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserUnverifiedEmailVerifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserUnverifiedEmailVerificationsRow
	for rows.Next() {
		var i GetUserUnverifiedEmailVerificationsRow
		if err := rows.Scan(
			&i.Email,
			&i.Code,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserEmailVerificationComplete = `-- name: IsUserEmailVerificationComplete :one
SELECT EXISTS(
    SELECT 1 FROM email_verifications
    WHERE user_id = ? AND email = ? AND verified_at IS NOT NULL
) AS is_verified
`

type IsUserEmailVerificationCompleteParams struct {
	UserID string
	Email  string
}

func (q *Queries) IsUserEmailVerificationComplete(ctx context.Context, arg IsUserEmailVerificationCompleteParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isUserEmailVerificationComplete, arg.UserID, arg.Email)
	var is_verified int64
	err := row.Scan(&is_verified)
	return is_verified, err
}

const recreateEmailVerification = `-- name: RecreateEmailVerification :exec
UPDATE email_verifications
SET code = ?, expires_at = ?, created_at = CURRENT_TIMESTAMP
WHERE user_id = ? AND email = ? AND verified_at IS NULL
`

type RecreateEmailVerificationParams struct {
	Code      string
	ExpiresAt time.Time
	UserID    string
	Email     string
}

func (q *Queries) RecreateEmailVerification(ctx context.Context, arg RecreateEmailVerificationParams) error {
	_, err := q.db.ExecContext(ctx, recreateEmailVerification,
		arg.Code,
		arg.ExpiresAt,
		arg.UserID,
		arg.Email,
	)
	return err
}
